name: CD

on:
  release:
    types: [created]

jobs:
  buildAndPush:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout Code
      - name: Extract tag name
        run: |
          echo "::set-env name=GIT_TAG::$(git tag --sort=-creatordate | head -n 1)"
      - name: Inject version number
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: Properties/AssemblyInfo.cs
        env:
          VERSION: ${{ env.GIT_TAG }}
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'
      - name: Restore NuGet packages
        run: nuget restore
      - name: Build solution
        run: msbuild Torii.sln /p:Configuration=Release
      - name: NuGet pack
        run: nuget pack Torii.csproj -Prop Configuration=Release
      - name: NuGet push
        run: nuget push Torii.${{ env.GIT_TAG }}.nupkg -Source https://api.nuget.org/v3/index.json