name: release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract tag name
        run: |
          echo "::set-env name=GIT_TAG::$(git tag --sort=-creatordate | head -n 1)"
      - name: Inject version number
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: "**"
        env:
          VERSION_NUMBER: ${{ env.GIT_TAG }}
      - name: Create template archive
        run: |
          tar -C ProjectTemplate -czvf com.figglewatts.torii.template.tgz package
      - name: Upload template archive to release
        uses: JasonEtco/upload-to-release@v0.1.1
        with:
          args: com.figglewatts.torii.template.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
